export default {
    INITIALIZE: 'INITIALIZE',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    ADD_INFLUENCER_TO_LIST: 'ADD_INFLUENCER_TO_LIST',
    INFLUENCER_RESULTS: 'INFLUENCER_RESULTS',
    ADD_FILTER: 'ADD_FILTER',
    REMOVE_FILTER: 'REMOVE_FILTER'
};