export default {
    INITIALIZE: 'INITIALIZE',
    RECEIVED_ERRORS: 'RECEIVED_ERRORS',

    // Filter-specific
    ADD_FILTER: 'ADD_FILTER',
    UPDATE_FILTERS: 'UPDATE_FILTERS',
    REMOVE_FILTER: 'REMOVE_FILTER',

    // User-specific
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',

    // Influencer-specific
    CREATE_INFLUENCER: 'CREATE_INFLUENCER',
    UPDATE_INFLUENCER: 'UPDATE_INFLUENCER',
    ADD_INFLUENCER_TO_LIST: 'ADD_INFLUENCER_TO_LIST',
    INFLUENCER_RESULTS: 'INFLUENCER_RESULTS',
    INFLUENCER_LIST_REFRESHED: 'INFLUENCER_LIST_REFRESHED',

    // Project-specific constants
    REFRESH_PROJECTS: 'REFRESH_PROJECTS',
    GET_PROJECT: 'GET_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',

    // Security-specific
    PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
    USER_FOUND_BY_RESET: 'USER_FOUND_BY_RESET'
};