export default {
    INITIALIZE: 'INITIALIZE',

    // Filter-specific
    UPDATE_FILTERS: 'UPDATE_FILTERS',
    RESET_FILTERS: 'RESET_FILTERS',

    // User-specific
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',

    // Influencer-specific
    CREATE_INFLUENCER: 'CREATE_INFLUENCER',
    UPDATE_INFLUENCER: 'UPDATE_INFLUENCER',
    ADD_INFLUENCER_TO_LIST: 'ADD_INFLUENCER_TO_LIST',
    INFLUENCER_RESULTS: 'INFLUENCER_RESULTS',
    INFLUENCER_LIST_REFRESHED: 'INFLUENCER_LIST_REFRESHED',

    // Project-specific constants
    REFRESH_PROJECTS: 'REFRESH_PROJECTS',
    GET_PROJECT: 'GET_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',

    // Campaign elements
    REFRESH_ELEMENTS: 'REFRESH_ELEMENTS',
    GET_ELEMENT: 'GET_ELEMENT',
    LIST_ELEMENT_ASSIGNEES: 'LIST_ELEMENT_ASSIGNEES',

    // Tasks
    REFRESH_TASKS: 'REFRESH_TASKS',
    CREATED_TASK: 'CREATED_TASK',
    FAILED_CREATING_TASK: 'FAILED_CREATING_TASK',
    UPDATED_TASK: 'UPDATED_TASK',
    FAILED_UPDATING_TASK: 'FAILED_UPDATING_TASK',

    // Comments
    REFRESH_COMMENTS: 'REFRESH_COMMENTS',

    // Lists
    REFRESH_LISTS: 'REFRESH_LISTS',
    GET_LIST: 'GET_LIST',
    CREATE_LIST: 'CREATE_LIST',
    UPDATE_LIST: 'UPDATE_LIST',
    DELETE_LIST: 'DELETE_LIST',
    ADD_LIST_TO_PROJECT: 'ADD_LIST_TO_PROJECT',

    // History
    GET_HISTORY: 'GET_HISTORY',

    // Assets
    REFRESH_ASSETS: 'REFRESH_ASSETS',

    // Security-specific
    PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
    USER_FOUND_BY_RESET: 'USER_FOUND_BY_RESET'
};